import './globals.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        {/* {process.env.NODE_ENV === 'development' && (
          <script src="http://localhost:8097"></script>
        )} */}
      </head>
      <body>{children}</body>
    </html>
  )
}
